deploy_app/config/routes.rb
Rails.application.routes.draw do
  root 'buildings#index'
  resources :buildings
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

deploy_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

deploy_app/app/models/building.rb
class Building < ApplicationRecord
end

deploy_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

deploy_app/app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :set_building, only: %i[ show edit update destroy ]

  # GET /buildings or /buildings.json
  def index
    @buildings = Building.all
  end

  # GET /buildings/1 or /buildings/1.json
  def show
  end

  # GET /buildings/new
  def new
    @building = Building.new
  end

  # GET /buildings/1/edit
  def edit
  end

  # POST /buildings or /buildings.json
  def create
    @building = Building.new(building_params)

    respond_to do |format|
      if @building.save
        format.html { redirect_to @building, notice: "Building was successfully created." }
        format.json { render :show, status: :created, location: @building }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buildings/1 or /buildings/1.json
  def update
    respond_to do |format|
      if @building.update(building_params)
        format.html { redirect_to @building, notice: "Building was successfully updated." }
        format.json { render :show, status: :ok, location: @building }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1 or /buildings/1.json
  def destroy
    @building.destroy
    respond_to do |format|
      format.html { redirect_to buildings_url, notice: "Building was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_building
      @building = Building.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def building_params
      params.require(:building).permit(:name, :address, :price, :station_name, :from_minutes)
    end
end

deploy_app/app/helpers/application_helper.rb
module ApplicationHelper
end

deploy_app/app/helpers/buildings_helper.rb
module BuildingsHelper
end

deploy_app/app/views/buildings/_form.html.erb
<%= form_with(model: building, local: true) do |form| %>
  <% if building.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(building.errors.count, "error") %> prohibited this building from being saved:</h2>

      <ul>
      <% building.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :station_name %>
    <%= form.text_field :station_name %>
  </div>

  <div class="field">
    <%= form.label :from_minutes %>
    <%= form.number_field :from_minutes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

deploy_app/app/views/buildings/edit.html.erb
<h1>Editing Building</h1>

<%= render 'form', building: @building %>

<%= link_to 'Show', @building %> |
<%= link_to 'Back', buildings_path %>

deploy_app/app/views/buildings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Buildings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Price</th>
      <th>Station name</th>
      <th>From minutes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buildings.each do |building| %>
      <tr>
        <td><%= building.name %></td>
        <td><%= building.address %></td>
        <td><%= building.price %></td>
        <td><%= building.station_name %></td>
        <td><%= building.from_minutes %></td>
        <td><%= link_to 'Show', building %></td>
        <td><%= link_to 'Edit', edit_building_path(building) %></td>
        <td><%= link_to 'Destroy', building, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Building', new_building_path %>

deploy_app/app/views/buildings/new.html.erb
<h1>New Building</h1>

<%= render 'form', building: @building %>

<%= link_to 'Back', buildings_path %>

deploy_app/app/views/buildings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @building.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @building.address %>
</p>

<p>
  <strong>Price:</strong>
  <%= @building.price %>
</p>

<p>
  <strong>Station name:</strong>
  <%= @building.station_name %>
</p>

<p>
  <strong>From minutes:</strong>
  <%= @building.from_minutes %>
</p>

<%= link_to 'Edit', edit_building_path(@building) %> |
<%= link_to 'Back', buildings_path %>

deploy_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeployApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>